### ISSUE TITLE
Example for the call of check_exchange_webservices

### ISSUE THREAD

**Issue by Terminator81** [NETWAYS/check_exchange_powershell#8]
could you please write example of check_exchange_webservices call ? 

I have saved the password for the user with "Get-Credential | Export-CliXml .\MailboxCredential.xml" but I always get the message "UNKNOWN: No Password set to check mailbox".

**Comment by martialblog** [comment]
Hi, 

this should work

```
Get-Credential | Export-CliXml ".\MailboxCredential.xml"
```

Are you sure it is store in ` $PSScriptRoot\MailboxCredential.xml` and the file is readable by the script.

You can also adjust the path with the parameter 'CredentialPath'
